# Generated by Django 5.1.1 on 2025-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_booking_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(default='82B1F5E1C1', max_length=10, unique=True),
        ),
    ]
